CDS-13 Add services card to services page
JE-Design/Clarity-Detailing-Solutions pull request #33
Opened 2020-08-20 05:13 UTC by Liannus

Changelog:
- Add services card to services page.

2020-08-20 16:11 UTC, forkball requested changes
Some changes to tailwind, otherwise good stuff.

2020-08-20 16:11 UTC, forkball commented on src/components/Service/Service.scss
> +      height: 400px;
Should be done with tailwind.

2020-08-20 16:11 UTC, forkball commented on src/components/Service/Service.scss
> +    height: 500px;
Should be done with tailwind.

2020-08-20 16:11 UTC, forkball commented on src/components/Service/Service.scss
> +      height: 300px;
Tailwind it up.

2020-08-21 02:19 UTC, Liannus commented on src/components/Service/Service.scss
> +      height: 400px;
Tailwind unfortunately caps out at 256 pixels as far as I know.

2020-08-21 02:19 UTC, Liannus commented on src/components/Service/Service.scss
> +    height: 500px;
See above

2020-08-21 02:19 UTC, Liannus commented on src/components/Service/Service.scss
> +      height: 300px;
See above

2020-08-21 14:47 UTC, forkball commented on src/components/Service/Service.scss
> +      height: 400px;
If that's the case, do they really need to be that large?

2020-08-21 22:11 UTC, Liannus commented on src/components/Service/Service.scss
> +      height: 400px;
Take a look, I believe they do.

Definitely a downside to tailwind.

2020-08-22 14:55 UTC, forkball commented on src/components/Service/Service.scss
> +      height: 400px;
Alright, we can settle then, not really a big deal. I checked em out and they looked good, we may want to do this to service images on landing.

2020-08-22 14:55 UTC, forkball approved these changes

2020-08-22 17:59 UTC, merged