CDS-11 Add testimony card
JE-Design/Clarity-Detailing-Solutions pull request #38
Opened 2020-08-21 19:18 UTC by ForkBombGIT

Changlog:
- Create testimony card
- Remove contact cards on testimony cards
- Add testimony cards to testimony page

2020-08-21 22:22 UTC, Liannus requested changes
Just some quick thoughts, need to look a bit deeper later.

2020-08-21 22:22 UTC, Liannus commented on src/components/Testimonial/Testimonial.jsx
> +        <img
Can we have an `object-fit: cover` style applied to this so it doesn't stretch?

2020-08-21 22:22 UTC, Liannus commented on src/components/Testimonial/Testimonial.jsx
> +        <h3 className="w-11/12">{customerName}</h3>
I think this heading should be centered with the image as it looks a bit odd as the card gets smaller.

Also maybe this shouldn't use dynamic fonts. Since the image doesn't change size the padding just gets larger and larger as the font gets smaller leaving an oddly large sized indent.

2020-08-22 14:59 UTC, forkball commented on src/components/Testimonial/Testimonial.jsx
> +        <img
Sure, although did you actually see the images stretch? Doesn't seem to happen when I resize.

2020-08-22 15:03 UTC, forkball commented on src/components/Testimonial/Testimonial.jsx
> +        <h3 className="w-11/12">{customerName}</h3>
Removed the dynamic header, looks a lot better. Take a look.

2020-08-22 16:02 UTC, Liannus commented on src/components/Testimonial/Testimonial.jsx
> +        <img
Yeah, It actually looks compressed right now which looks kind of odd

2020-08-22 16:05 UTC, Liannus commented on src/components/Testimonial/Testimonial.jsx
> +        <h3 className="w-11/12">{customerName}</h3>
Agreed, way better.

2020-08-22 19:19 UTC, forkball commented on src/components/Testimonial/Testimonial.jsx
> +        <img
Okay, I added but I really don't see a visible difference

2020-08-23 22:19 UTC, Liannus commented on src/components/Testimonial/Testimonial.jsx
> +        <img
Looks like it got added in the wrong spot, I threw it on in a commit if you want to see where I meant.

2020-08-23 22:19 UTC, Liannus approved these changes
Looks good now.

2020-08-23 22:31 UTC, merged